apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      serviceAccountName: cm-incluster
      containers:
        - name: nginx
          image: acs107802/incluster:latest
          imagePullPolicy: IfNotPresent
